apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-agent-config
  namespace: appdynamics
data:
  APPDYNAMICS_PROTOCOL: http
  APPDYNAMICS_CONTROLLER_HOST: controller-4517nosshco-ixoarnbx.appd-cx.com
  APPDYNAMICS_CONTROLLER_PORT: "8090" 
  APPDYNAMICS_EVENTS_API_URL: "http://controller-4517nosshco-ixoarnbx.appd-cx.com:9080"
  APPDYNAMICS_ACCOUNT_NAME: customer1
  APPDYNAMICS_GLOBAL_ACCOUNT_NAME: customer1_b9005dda-07af-4393-a1d3-e5a005af3870

