apiVersion: apps/v1
kind: Deployment
metadata:
  name: wcf-console-app
  namespace: appdynamics
spec:
  selector:
    matchLabels:
      name: wcf-console-app
  replicas: 1
  template:
    metadata:
      labels:
        name: wcf-console-app
    spec:
      nodeSelector:
        beta.kubernetes.io/os: windows
        #cloud.google.com/gke-nodepool: windows-pool
     # tolerations:
      #- key: "node.kubernetes.io/os"
       # operator: "Equal"
        #value: "windows"
        #effect: "NoSchedule"
      containers:
      - name: wcf-console-app
        envFrom:
        - configMapRef:
            name: agent-config
        env:
        - name: APPDYNAMICS.AGENT.ACCOUNTACCESSKEY
          valueFrom:
            secretKeyRef:
              key: appd-key
              name: appd-secret
        - name: APPDYNAMICS_AGENT_APPLICATION_NAME
          value: test-application
        - name: APPDYNAMICS_AGENT_TIER_NAME
          value: wcf-console-app
        image: docker.io/iogbole/wcf-console-client
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: wcf-console-app
  namespace: appdynamics
spec:
  selector:
    name: wcf-console-app
   #type: loadBalancer
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    protocol: TCP
status:
  loadBalancer: {}