apiVersion: v1
kind: ServiceAccount
metadata:
  name: appdynamics-infraviz
---
apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: appd-infra-agent-windows
spec: 
  selector:
    matchLabels:
      name: appd-infra-agent-windows
  template: 
    metadata: 
      labels: 
        name: appd-infra-agent-windows
    spec:
      nodeSelector:
        kubernetes.io/os: windows
        kubernetes.io/arch: amd64
      serviceAccountName: appdynamics-infraviz
      containers:
      - name: appd-windows-infra-agent
        image:  appdynamics/machine-agent-analytics:20.6.0-win-ltsc2019
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: ma-config
        env:
        - name:  APPDYNAMICS_AGENT_UNIQUE_HOST_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: appd-key
              name: appd-secret
        resources:
          limits:
            cpu: "0.6"
            memory: "2Gi"
          requests:
            cpu: "0.3"
            memory: "1G"
        ports:
          - containerPort: 9090
      restartPolicy: Always   
---
apiVersion: v1
kind: Service
metadata:
  name: appd-infra-agent-service-windows
spec:
  selector:
    name: appd-infra-agent-windows
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090 
status:
  loadBalancer: {}