apiVersion: v1
data:

  APPDYNAMICS_AGENT_ACCOUNT_NAME: customer1
  APPDYNAMICS_AGENT_GLOBAL_ACCOUNT_NAME: customer1_282fa861-554e-4073-bttrrr
  APPDYNAMICS_CONTROLLER_HOST_NAME: customer.saas.appdynamics.com
  APPDYNAMICS_CONTROLLER_PORT: "443"
  APPDYNAMICS_CONTROLLER_SSL_ENABLED: "true"
  EVENT_ENDPOINT: https://fra-ana-api.saas.appdynamics.com:443 
  APPDYNAMICS_SIM_ENABLED: "true" 
 
  #optional 

  #APPDYNAMICS_AGENT_UNIQUE_HOST_ID="" #defaults to containerID 
  #APPDYNAMICS_AGENT_APPLICATION_NAME="" #defaults to analytics_agent_{containerID}

  #APPDYNAMICS_DOTNET_COMPATIBILITY_MODE: "true"  
  #APPDYNAMICS_ANALYTICS_AGENT_PORT: "9090" #defaults to 9090
  #APPDYNAMICS_ENABLE_ANALYTICS_AGENT: "true" #defaults to true
  #APPDYNAMICS_MACHINE_HIERARCHY_PATH=AWS|PROD|EU-WEST2|WorkerNodes| #optional and must end with a | when specified
  #APPDYNAMICS_AGENT_METRIC_LIMIT="" 

  #APPDYNAMICS_AGENT_PROXY_HOST="" 
  #APPDYNAMICS_AGENT_PROXY_USER="" 
  #APPDYNAMICS_AGENT_PROXY_PORT="" 
  #APPDYNAMICS_AGENT_PROXY_PASS="" 
  #APPDYANMICS_PROXY_PASSWORD_FILE: ""

  #APPDYNAMICS_AGENT_HTTPS_PROXY_PORT=""
  #APPDYNAMICS_AGENT_HTTPS_PROXY_PORT=""
  #APPDYNAMICS_AGENT_HTTPS_PROXY_HOST="
  
kind: ConfigMap
metadata:
  name: windows-ma-config