apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-agent-config
  namespace: appdynamics
data:
  APPDYNAMICS_PROTOCOL: http
  APPDYNAMICS_CONTROLLER_HOST: controller2030-2033nos-vxuzyg4j.appd-cx.com
  APPDYNAMICS_CONTROLLER_PORT: "8090" 
  APPDYNAMICS_EVENTS_API_URL: "http://controller2030-2033nos-vxuzyg4j.appd-cx.com:9080"
  APPDYNAMICS_ACCOUNT_NAME: customer1
  APPDYNAMICS_GLOBAL_ACCOUNT_NAME: customer1_b8502d8b-1abc-472c-b825-f3ff8e61b075

