apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-checker-service
spec:
  selector:
    matchLabels:
      app: resource-checker-service
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: resource-checker-service
        tier: backend
        track: stable
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      volumes:
        - name: appd-dotnet-agent
          emptyDir: {}
        - name: log-volume
          emptyDir: {}
      initContainers:
        - name:  micro-dotnet-agent
          image: iogbole/micro-dotnet-agent:20.6
          command: ["pwsh", "-command", "copy-item -path c:/appdynamics/dotnet-agent/* -destination c:/appd-dotnet-agent -Recurse"]
          volumeMounts:
          - mountPath: "c:/appd-dotnet-agent"
            name: appd-dotnet-agent
      containers:
      - name: resource-checker-service
        image: iogbole/console_resouce_checker:initcontainer
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: "c:/appdynamics/dotnet-agent"
            name: appd-dotnet-agent
          - name: log-volume
            mountPath: "c:/resource-check/logs"
        resources: {}
        env: 
        - name: APPDYNAMICS.AGENT.ACCOUNTACCESSKEY
          valueFrom:
              secretKeyRef: 
                 name: appd-secret
                 key: appd-key
        - name: APPDYNAMICS.AGENT.APPLICATIONNAME
          value: winContainer-Demo
        - name:  APPDYNAMICS_AGENT_TIER_NAME
          value: resource-checker
        ##### PLEASE READ #########
        # It is recommended to hard code the value of APPDYNAMICS_AGENT_NODE_NAME env if the instrumented (.exe)
        # app is designed and expected to always have 1 replica. For example, <tier_name>_1. 
        # If the instrumented application scales to > 1 replicas, it is recommended to pass a dynamic node using 
        # the pod or container information as show below. Please refer to this doc for further detail. 
        # https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/
        - name: APPDYNAMICS_AGENT_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: APPDYNAMICS_AGENT_UNIQUE_HOST_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName  
        envFrom:
          - configMapRef:
              name: micro-dotnet-agent-config
      - name: appd-log-analytics
        image: iogbole/analytics-agent:20.6.0-win
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "c:/logdir"
          name: log-volume
        ports:
        - containerPort: 9090
          protocol: TCP
        resources: {}
        envFrom:
        - configMapRef:
            name: analytics-agent-config
        env:
        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: appd-key
              name: appd-secret
        - name: APPDYNAMICS_AGENT_APPLICATION_NAME
          value: "windows|component|application"