apiVersion: apps/v1
kind: Deployment
metadata:
  name: io-service-checker
  # namespace: appdynamics
spec:
  selector:
    matchLabels:
      name: io-service-checker
  replicas: 1
  template:
    metadata:
      labels:
        name: io-service-checker
    spec:
      nodeSelector:
        beta.kubernetes.io/os: windows
        kubernetes.io/os: windows
        kubernetes.io/arch: amd64
        #cloud.google.com/gke-nodepool: windows-pool
      #tolerations:
      #- key: "node.kubernetes.io/os"
      #  operator: "Equal"
      #  value: "windows"
      #  effect: "NoSchedule"
      containers:
      - name: io-service-checker
        envFrom:
        - configMapRef:
            name: agent-config
        env:
        - name: APPDYNAMICS.AGENT.ACCOUNTACCESSKEY
          valueFrom:
            secretKeyRef:
              key: appd-key
              name: appd-secret
        - name: APPDYNAMICS_AGENT_APPLICATION_NAME
          value: test-application
        - name: APPDYNAMICS_AGENT_TIER_NAME
          value: io-service-checker
        - name: APPDYNAMICS.APPLICATION.EXECUTABLE.FULLPATH
          value: IOServiceCheckerApp.exe
        - name: APPDYNAMICS.AGENT.RUNTIME.REINSTRUMENTATION.ENABLED
          value: true
        image: docker.io/iogbole/ioservicechecker:latest
        imagePullPolicy: Always
        resources:
         limits:
            memory: 500Mi
            cpu: 1
         requests:
            memory: 300Mi
            cpu: 0.6
      dnsPolicy: ClusterFirst
      restartPolicy: Always